### ISSUE TITLE
Support Prettier v3

### ISSUE THREAD

**Issue by Gudahtt** [Gudahtt/prettier-plugin-sort-json#119]
This plugin should support Prettier v3.

See here for instructions: https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

**Comment by Gudahtt** [comment]
I will wait on this until the Prettier types have been updated

**Comment by Gudahtt** [comment]
Absolutely, thanks for the reminder!

**Comment by mjsteinbaugh** [comment]
Hi @Gudahtt I just tried installing v2.0.0 with prettier 3.0.2 and I'm still not seeing the `--json-recursive-sort` option in `prettier --help` like with prettier v2.

I see that prettier v3 has a `--plugin <path>` option. Do I need to set that?

**Comment by Gudahtt** [comment]
@mjsteinbaugh v2 still only supports Prettier v2. I am preparing a v3 release now that will support Prettier v3 though! It will be available momentarily.

But yes, you are correct that plugins need to be explicitly loaded with Prettier v3. See these instructions for further details: https://prettier.io/docs/en/plugins#using-plugins

**Comment by mjsteinbaugh** [comment]
Nice! I'll try out 3.0.0 today awesome thanks

**Comment by ssbarnea** [comment]
@mjsteinbaugh Were you able to make v3 of prettier and this plugin work because I failed, at least when using pre-commit. For some reason prettier fails to find the plugin and the reason I am saying this is that I see these when it is running:
```
[warn] Ignored unknown option { jsonRecursiveSort: true }.
```

My pre-commit hook config looks like:
```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        verbose: true
        always_run: true
        additional_dependencies:
          - prettier@3.0.3
          - prettier-plugin-toml@1.0.0
          - prettier-plugin-sort-json@3.0.1
```

I don't even think that this has anything to do with global because at least the pre-commit installation method should not require that.
