### ISSUE TITLE
Specify custom sort algorithm

### ISSUE THREAD

**Issue by MasterEric** [Gudahtt/prettier-plugin-sort-json#27]
Currently the plugin only allows sorting JSON keys using the default sort order. (The default sort order is ascending, built upon converting the elements into strings, then comparing their sequences of UTF-16 code units values.) Ideally, this plugin would allow for the customization of the sorting algorithm used via configuration. 

We could have a set of presets available, but instead for maximum flexibility I would like the user to be able to specify a function with the signature `function(a: any, b: any): int` [as described here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) which will be passed as an argument to `Object.keys(object).sort()` here:

https://github.com/Gudahtt/prettier-plugin-sort-json/blob/main/index.ts#L13

Note that ([as specified by Prettier](https://github.com/prettier/prettier/blob/12bddae20c0bd6c31c53ec44656868f21ec5aca7/src/main/core-options.js#L17)) options can only be an `int`, `boolean`, `choice`, or `path`.

Here is my proposal:

```yaml
printWidth: 90
tabWidth: 4
overrides:
  - files: "**/data/*.json"
    options:
      plugins:
        - "./node_modules/prettier-plugin-sort-json"
      jsonRecursiveSort: true
      jsonObjectSortAlgorithm: "./config/sortFunction.js"
      jsonArraySortAlgorithm: "./config/sortFunctionB.js"
```

`./config/sortFunction.js` is a JavaScript file with contents like such:

```
export default (a, b) => {
  if (a < b) {
    return -1;
  } else if (a > b) {
    return 1;
  }
  return 0;
};
```

This scheme is highly flexible; any desired sorting algorithm can be used, a custom pre-defined order can be defined simply by comparing with a constant array, and with the Prettier configuration system that already exists, different sorting algorithms could be used for different files.
